# Generated by Django 5.0.1 on 2024-01-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='gallery')),
                ('desc', models.TextField()),
            ],
        ),
    ]
