# Generated by Django 5.0.1 on 2024-01-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Place',
        ),
    ]
